# Site settings
title: Berliner Blockflöten Orchester
browser_title: Berliner Blockflöten Orchester - BBO | Blockflöte spielen
email: berlinerblockfloetenorchester@web.de
description: > # this means to ignore newlines until "baseurl:"
  Das Berliner Blockflöten Orchester ist eine Blockflöten Ensemble das anspruchsvolle Werke aller Epoche spielt. Leitung: Simon Borutzki
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.berliner-blockfloeten-orchester.de" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
